id: IE3339CB2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:30:43+00:00'
last_modified: '2022-06-08T08:47:43.790795+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29489
  title: རོ་ལངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CF05:
      image_group_id: I1KG23004
      title: ''
      total_pages: 202
      order: 1
      base_file: CF05.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
