id: P009124
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:08.121046
source_metadata:
  id: bdr:W29489
  title: རོ་ལངས།
  author: ''
  volumes:
    4d36b71857ce4188a8285b19106da9d0:
      image_group_id: I1KG23004
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
